### ISSUE TITLE
gret-0.0.1.zip throws an error when trying to enable addon after installation

### ISSUE THREAD

**Issue by DiveBombDrg** [greisane/gret#1]
changing the folder name to just gret seemed to have fixed the issue 
![image](https://user-images.githubusercontent.com/34082449/119395247-16431000-bc88-11eb-9dbc-05c4e8db9993.png)

![image](https://user-images.githubusercontent.com/34082449/119395321-307cee00-bc88-11eb-99bb-cee684a6ab87.png)

**Comment by greisane** [comment]
Thanks, guess Blender doesn't like dots. Fixed by changing the release tag to 0_0_1.
