### ISSUE TITLE
Request: add handling for converting Blender poses to unreal pose assets.

### ISSUE THREAD

**Issue by BusterCharlie** [greisane/gret#10]
Blender poses only want the posed bones to have keyframes data.  Unreal pose assets require zero transforms keyframes. For exporting a blender pose (for example for faceARKit face shapes) to unreal I need to manually keyframe the rest pose along with the changed bones. But this break's blenders about to blend poses.

Is there a way to add an option to automatically add or strip zero keyframes from an animation to allow non destructive conversion between blender and unreal poses?

**Comment by greisane** [comment]
Baking the action would keyframe every bone, isn't this what you want?

> Is there a way to add an option

Add an option to what?

**Comment by greisane** [comment]
Can't help without more details.
