### ISSUE TITLE
Shapekey panel options missing from Lattice objects

### ISSUE THREAD

**Issue by Da-Nuker** [greisane/gret#13]
The standard shapekey manipulation options for Lattice objects are missing compared to Mesh objects.

The shapekey presets features of this addon also does not show up for Lattice objects.

![lattice shapekeys](https://user-images.githubusercontent.com/30483443/236632755-e9ab1d47-3cf5-476c-bee6-74fc5a7bf1eb.png)

Thanks for the great addon by the way!

**Comment by greisane** [comment]
Wow you're right, what a blunder. Fixed in aa25645c93fa390aba3038a0bfaf8bdbca1ddefd and b174cf5cd3403b4ffe05a54018fe7c12dcfbdf31, I'll add a new release shortly.
No problem, glad you find it useful!
