### ISSUE TITLE
Make collision not working in Blender 4.0 (from lastest commit)

### ISSUE THREAD

**Issue by narredev** [greisane/gret#15]
Started transitioning to Blender 4, decided to update this addon from the latest commit (On Nov 16) since I saw some fixes for 4.1
Sorry if the addon is not yet intended for 4.0!

When using "Make Collision" with any shape, this error appears:

bpy.ops.gret.collision_make(shape='AABB', location=(0, 0, 0), aabb_width=2, aabb_height=2, aabb_depth=2, cyl_radius1=1.41421, cyl_radius2=1.41421, cyl_height=2, cap_radius=1.41421, cap_depth=0.585786, cap_rotation=(-3.14159, -1.5708, 0), sph_radius=2)

Python: Traceback (most recent call last):
  File "C:\Users\*******\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\gret-master\helpers.py", line 431, in try_call
    func(*args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

Most of the other options I use work fine but didn't try them all!

**Comment by greisane** [comment]
Thank you for the report! And yeah I'm aware a bunch of stuff is broken. I'll get around to drafting a new release soon.

**Comment by greisane** [comment]
Sorry it took a while! Fixed in 021a6e9e65779a8773239f6d79dbfd0e1bb2189d and added a new release.
