### ISSUE TITLE
Trying to merge only gives error

### ISSUE THREAD

**Issue by AmanGaming** [greisane/gret#5]
![image](https://user-images.githubusercontent.com/39135863/140093470-84c8cfd5-e772-4677-96ff-90d91d6196ca.png)

**Comment by AmanGaming** [comment]
It still kinda works but I just keep getting that error. don't know if it is affecting anything/

**Comment by greisane** [comment]
Fixed in c5b9ca9e72cbd4099f97d87c54518383002ca7a3. Going forward I'll require Blender 2.93 since I'm not really able to test everything in both versions.
